In [2]:
"""
課題：行列積の実装
　　　以下の行列積を利用
   　 import numpy as np
      a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
      b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
      
【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。
計算過程もマークダウンテキストを用いて説明してください。
"""



'\n課題：行列積の実装\n\u3000\u3000\u3000以下の行列積を利用\n   \u3000 import numpy as np\n      a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])\n      b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])\n      \n【問題1】行列積を手計算する\nAとBの行列積を手計算で解いてください。\n計算過程もマークダウンテキストを用いて説明してください。\n'

与えられた式は以下の通り

$$
A=\left[
\begin{matrix} -1 & 2 & 3 \\ 4 & -5 & 6 \\ 7 & 8 & -9 \end{matrix}
\right], 
B=\left[
\begin{matrix} 0 & 2 & 1 \\ 0 & 2 & -8 \\ 2 & 9 & -1 \end{matrix}
\right]
$$

この行列積を手計算する\
行列積の求め方は行と列を掛け合わせていく

$$
A×B= 
\left[
\begin{matrix} -1×0+2×0+3×2 & -1×2+2×2+3×9 & -1×1+2×-8+3×-1 \\ 4×0+-5×0+6×2 & 4×2+-5×2+6×9 & 4×1+-5×-8+6×-1 \\ 7×0+8×0+-9×2 & 7×2+8×2+-9×9 & 7×1+8×-8+-9×-1 \end{matrix}
\right]
$$

すると

$$
= 
\left[
\begin{matrix} 6 & 29 & -20 \\ 12 & 10 & 38 \\ -18 & -51 & -48 \end{matrix}
\right]
$$

になる



In [3]:
"""
【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。
これらを使い行列積を計算してください。


"""
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print(np.matmul(a_ndarray,b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [11]:
"""
【問題3】ある要素の計算を実装
NumPyのnp.matmul()やnp.dot()、または@演算子を使わずに計算
行列Aの(0,0)の要素 $a_{0, 0}$ と行列Bの(0,0)の要素 $b_{0, 0}$ を掛け合わせる
行列Aの(0,1)の要素 $a_{0, 1}$ と行列Bの(1,0)の要素 $b_{1, 0}$ を掛け合わせる
行列Aの(0,2)の要素 $a_{0, 2}$ と行列Bの(2,0)の要素 $b_{2, 0}$ を掛け合わせる
それらの値をすべて足し合わせる

"""

#まず空の行列を作成する
ab_ndarray = np.full((3,3),0)
print(ab_ndarray)

#それぞれの和を代入していく                      
ab_ndarray[0][0] = a_ndarray[0][0]*b_ndarray[0][0]+a_ndarray[0][1]*b_ndarray[1][0]+a_ndarray[0][2]*b_ndarray[2][0]
ab_ndarray[0][1] = a_ndarray[0][0]*b_ndarray[0][1]+a_ndarray[0][1]*b_ndarray[1][1]+a_ndarray[0][2]*b_ndarray[2][1]
ab_ndarray[0][2] = a_ndarray[0][0]*b_ndarray[0][2]+a_ndarray[0][1]*b_ndarray[1][2]+a_ndarray[0][2]*b_ndarray[2][2]

ab_ndarray[1][0] = a_ndarray[1][0]*b_ndarray[0][0]+a_ndarray[1][1]*b_ndarray[1][0]+a_ndarray[1][2]*b_ndarray[2][0]
ab_ndarray[1][1] = a_ndarray[1][0]*b_ndarray[0][1]+a_ndarray[1][1]*b_ndarray[1][1]+a_ndarray[1][2]*b_ndarray[2][1]
ab_ndarray[1][2] = a_ndarray[1][0]*b_ndarray[0][2]+a_ndarray[1][1]*b_ndarray[1][2]+a_ndarray[1][2]*b_ndarray[2][2]

ab_ndarray[2][0] = a_ndarray[2][0]*b_ndarray[0][0]+a_ndarray[2][1]*b_ndarray[1][0]+a_ndarray[2][2]*b_ndarray[2][0]
ab_ndarray[2][1] = a_ndarray[2][0]*b_ndarray[0][1]+a_ndarray[2][1]*b_ndarray[1][1]+a_ndarray[2][2]*b_ndarray[2][1]
ab_ndarray[2][2] = a_ndarray[2][0]*b_ndarray[0][2]+a_ndarray[2][1]*b_ndarray[1][2]+a_ndarray[2][2]*b_ndarray[2][2]

#計算結果の出力
print(ab_ndarray)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [168]:
"""
【問題4】行列積を行う関数の作成
行列AとBを引数に受け取り、行列積を返す関数としてください。
"""

any_ndarray1 = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
any_ndarray2 = np.array([[1, 2, 3], [4, 5, -6], [7, 8, -9]])
print(np.matmul(any_ndarray1,any_ndarray2))

def matrix_product(any_ndarray1= np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]]), any_ndarray2= np.array([[1, 2, 3], [4, 5, -6], [7, 8, -9]])):
    answer_ndarray = np.full((int(any_ndarray1.shape[0]),int(any_ndarray2.shape[1])),0)
    
    if(any_ndarray1.shape[1]==any_ndarray2.shape[0]):
        for i in range(any_ndarray1.shape[0]):
            for j in range(any_ndarray2.shape[1]):
                for k in range(any_ndarray2.shape[0]):
                    answer_ndarray[i][j] = answer_ndarray[i][j] + any_ndarray1[i][k] * any_ndarray2[k][j]
        print(answer_ndarray)
    else:
        print("一つ目の行列の列数と二つ目の行列の行数が異なるので計算できません。")
        
matrix_product()


[[ 28  32 -42]
 [ 26  31 -12]
 [-24 -18  54]]
[[ 28  32 -42]
 [ 26  31 -12]
 [-24 -18  54]]


In [165]:
"""
【問題5】行列積を行う関数の作成
力される形に問題があることをprint()を使い表示するコードを書き加えてください。
"""
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

matrix_product(any_ndarray1 = d_ndarray, any_ndarray2 = e_ndarray)
print(np.matmul(d_ndarray,e_ndarray))


一つ目の行列の列数と二つ目の行列の行数が異なるので計算できません。


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [166]:
"""
【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。
"""

matrix_product(any_ndarray1 = d_ndarray, any_ndarray2 = np.transpose(e_ndarray))
print(np.matmul(d_ndarray,np.transpose(e_ndarray)))

[[ 46  -4]
 [-34  73]]
[[ 46  -4]
 [-34  73]]
